defmodule Api.Repo.Migrations.SwitchToAttributeTenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:nome, :text, null: false)
      add(:email, :citext, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:professionals, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:nome, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:clinic_id, :uuid, null: false)
    end

    create table(:memberships, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:papel, :text, null: false, default: "recepcao")
      add(:status, :text, null: false, default: "pendente")
      add(:professional_id, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "memberships_user_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )

      add(:clinic_id, :uuid, null: false)
    end

    create unique_index(:memberships, [:clinic_id, :professional_id],
             name: "memberships_unique_professional_link_index"
           )

    create unique_index(:memberships, [:user_id, :clinic_id],
             name: "memberships_unique_user_per_clinic_index"
           )

    create table(:clinics, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:professionals) do
      modify(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "professionals_clinic_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:memberships) do
      modify(
        :clinic_id,
        references(:clinics,
          column: :id,
          name: "memberships_clinic_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    alter table(:clinics) do
      add(:nome, :text, null: false)
      add(:timezone, :text, null: false, default: "America/Sao_Paulo")
      add(:cap_turma_padrao, :bigint, null: false, default: 4)
      add(:falta_consome_padrao, :boolean, null: false, default: false)
      add(:slot_minutos, :bigint, null: false, default: 15)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    alter table(:clinics) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:slot_minutos)
      remove(:falta_consome_padrao)
      remove(:cap_turma_padrao)
      remove(:timezone)
      remove(:nome)
    end

    drop(constraint(:memberships, "memberships_clinic_id_fkey"))

    alter table(:memberships) do
      modify(:clinic_id, :uuid)
    end

    drop(constraint(:professionals, "professionals_clinic_id_fkey"))

    alter table(:professionals) do
      modify(:clinic_id, :uuid)
    end

    drop(table(:clinics))

    drop(constraint(:memberships, "memberships_user_id_fkey"))

    drop_if_exists(
      unique_index(:memberships, [:user_id, :clinic_id],
        name: "memberships_unique_user_per_clinic_index"
      )
    )

    drop_if_exists(
      unique_index(:memberships, [:clinic_id, :professional_id],
        name: "memberships_unique_professional_link_index"
      )
    )

    drop(table(:memberships))

    drop(table(:professionals))

    drop_if_exists(unique_index(:users, [:email], name: "users_unique_email_index"))

    drop(table(:users))
  end
end
